baseURL = 'https://pt-10.github.io/'
languageCode = 'en-us'
title = 'Prashant Tandon'
theme = 'hugo-PaperMod'
publishdir = 'docs'

[params]
  toc = true
  tocStartLevel = 2
  tocEndLevel = 5
  tocHideOnMobile = false
  tocFloating = true
  ShowReadingTime = true
  ShowShareButtons = false
  ShowCodeCopyButtons = true
  disableSpecial1stPost = true
  hideSummary = true
  hideHomeContent = true
  mainSections = []
  ShowAllPagesInArchive = true
  disableTOC = false


  [params.assets]
  customCSS = ["css/custom.css"]
  disableFingerprinting = true
  favicon = "favicon.ico"

  [params.math]
  enable = true

  [params.search]
  enabled = true

  [params.homeInfoParams]
  Title = "Hi, this is Prashant!"
  Content = """
  <div style="display: flex; align-items: flex-start; justify-content: space-between; margin-top: 1rem; gap: 1rem;">
    <div style="flex: 3; text-align: left;">
      <p style="margin: 0.5rem 0;">A recent grad from IIT Jodhpur, having majored in AI.</p>
      <p style="margin: 0.5rem 0;">I dabble with models and enjoy experimenting across modalities. I take interest in quite a few things: <br> autonomous driving, audio synthesis, deep learning for trading and financial investments, model inferences, llm reasoning, reinforcement learning - to name a few.</p>
      <p style="margin: 0.5rem 0;">Neurospiking agents have piqued my interest recently and in the future I intend to explore model architectures that are more biologically aligned. </p>
    </div>
    <div style="flex: 1.5; margin-left: 1rem; display: flex; align-items: center;">
      <img src="images/profile.png" class="profile-img dark-img" style="border-radius: 8px; object-fit: cover; width: 100%; height: auto;" />
    </div>
  </div>
  <p style="margin: 0.5rem 0;"><strong>Unpopular opinion</strong> – LLMs don't reason and are at the end of the day just next token predictors. Reasoning is philosophical and goes beyond mere definition, read more <a href="https://plato.stanford.edu/entries/chinese-room" target="_blank">here</a>.</p>
<p style="margin: 0.5rem 0; padding-left: 0.8rem; border-left: 3px solid #a0a0a0;">
  I’m currently <strong>seeking research-oriented roles both in academia and industry</strong> that challenge the status quo and help unlock new frontiers in deep learning and AI.
</p>



  """



[[params.socialIcons]]
name = "github"
url = "https://github.com/pt-10"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/yourhandle"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/prashant-tandon-4a7678249/"


[markup]
  [markup.goldmark.renderer]
    unsafe = true

[outputs]
home = ["HTML", "RSS", "JSON"]
section = ["HTML", "RSS"]
page = ["HTML"]
taxonomy = ["HTML"]
taxonomyTerm = ["HTML"]
archive = ["HTML"]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "Search"
    url = "/search/"
    weight = 4

  [[menu.main]]
    name = "Archive"
    url = "/archives/"
    weight = 5
